# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-03-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_auto_20230328_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
