# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-03-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_auto_20230330_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='just_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
