# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-03-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0004_adminuser_just_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
