# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-03-30 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0011_auto_20230330_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='just_datetime',
        ),
    ]
