# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-03-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0012_auto_20230330_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='just_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
